<?php

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;

?>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<form method="post" class="wt-page-options wt-page-options-relationships-chart d-print-none">
    <?= csrf_field() ?>

    <?php if ($beforeJD !== null): ?>
      <input type="hidden" name="beforeJD" value="<?php echo $beforeJD ?>">
    <?php endif; ?>
    <input type="hidden" name="recursion" value="<?php echo $recursion ?>">
      
    <div class="row form-group">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="xref">
            <?= MoreI18N::xlate('Individual 1') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select-individual', ['name' => 'xref', 'individual' => $individual1, 'tree' => $tree, 'required' => true]) ?>
        </div>
    </div>

    <div class="row form-group">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="xref2">
            <?= MoreI18N::xlate('Individual 2') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select-individual', ['name' => 'xref2', 'individual' => $individual2, 'tree' => $tree, 'required' => true]) ?>
        </div>
    </div>

    <?php if (!empty($ancestors_options1)) : ?>
      <fieldset class="form-group">
          <div class="row">
              <legend class="col-form-label col-sm-3 wt-page-options-label">
              </legend>
              <div class="col-sm-9 wt-page-options-value">
                  <?= view('components/radios', ['name' => 'ancestors', 'options' => $ancestors_options1, 'selected' => $ancestors]) ?>
              </div>
          </div>
      </fieldset>
    <?php endif ?>

    <?php if (!empty($ancestors_options2)) : ?>
      <fieldset class="form-group">
          <div class="row">
              <legend class="col-form-label col-sm-3 wt-page-options-label">
                  <?php if ($dateDisplay !== null) : ?>
                    <?= I18N::translate('Options referring to overall connections established before %1$s.', $dateDisplay) ?>
                  <?php endif ?>
              </legend>
              <div class="col-sm-9 wt-page-options-value">
                  <?= view('components/radios', ['name' => 'ancestors', 'options' => $ancestors_options2, 'selected' => $ancestors]) ?>
              </div>
          </div>
      </fieldset>
    <?php endif ?>

    <div class="row form-group">
        <div class="col-form-label col-sm-3 wt-page-options-label"></div>
        <div class="col-sm-9 wt-page-options-value">
            <button class="btn btn-primary" type="submit">
                <?= /* I18N: A button label. */ MoreI18N::xlate('view') ?>
            </button>

            <button class="btn btn-link" id="btn-swap-individuals" type="button">
                <?= /* I18N: Reverse the order of two individuals */
                MoreI18N::xlate('Swap individuals') ?>
            </button>
        </div>
    </div>
</form>

<?php if ($individual1 !== null && $individual2 !== null) : ?>
    <div class="wt-ajax-load wt-page-content wt-chart wt-chart-relationships" data-wt-ajax-url="<?= e($ajax_url) ?>"></div>
<?php endif ?>

<?php View::push('javascript') ?>
<script>
  $('#btn-swap-individuals').click(function () {
      // Swap the name attributes
      document.getElementById("xref").name = "xref2";
      document.getElementById("xref2").name = "xref";
      document.querySelector(".wt-page-options-relationships-chart").submit();
  });
</script>
<?php View::endpush() ?>

<!-- for help text -->
<!-- 
help text is only used in the 'Chart' view but we need the support here, 
because it uses document.addEventListener("DOMContentLoaded",
and the 'Chart' view is loaded after that!
-->
<?= view('modals/ajax') ?>
