<?php use Fisharebest\Webtrees\I18N; ?>
<?php use Fisharebest\Webtrees\View; ?>

<?= view('components/breadcrumbs', ['links' => [route('admin-control-panel') => I18N::translate('Control panel'), route('modules') => I18N::translate('Modules'), $title]]) ?>

<h1><?= $title ?></h1>

<p class="small text-muted">
	<?php echo I18N::translate('This process calculates dates for all INDI - FAM links, so that relationships at a specific point in time can be calculated efficiently.') ?>
</p>
<p class="small text-muted">
	<?php echo I18N::translate('For large trees, this process may initially take several minutes. You can always safely abort and continue later.') ?>
</p>
<p class="small text-muted">
	<?php echo I18N::translate('The process should be repeated whenever a tree is edited, otherwise you may obtain inconsistent relationship data (displayed relationships are always valid, but they may not actually have been established at the given date, if changes in the tree are not synchronized here).') ?>
</p>

<div id="sync" class="col-xs-12">
	<div class="progress">
		<?php echo I18N::translate('Calculating…'); ?>
	</div>
</div>

<?php View::push('javascript'); ?>
	<script>
		//empty javascript object used to trigger POST
		$("#sync").load("<?= $post ?>", {});
	</script>
<?php View::endpush() ?>
