<?php

declare(strict_types=1);

use Cissee\WebtreesExt\Services\TreeNode;
use Cissee\WebtreesExt\Services\TreeNodeMarkupType;
use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\I18N;

/**
 * @var TreeNode $node
 */

$record = $node->record();

if ($record instanceof Family) {
  throw new Exception();  
}

$indiMarkup = $node->markup();
$indiData = $node->data();
    
$next = $node->next();
    
$leavesOnly = true;    
foreach ($next as $nextNode) {
    $nextnext = $nextNode->next();
    if (sizeof($nextnext) > 0) {
        $leavesOnly = false;
        break;
    }
}

$leaves = "";
if ($leavesOnly) {
    $leaves = " ⚶-fam-leaves";
}

?>

<ol class="⚶-famc">
    <li class="⚶-famc">
        <div class="⚶-famc">
            <?php if ($indiMarkup !== null) : ?>
                <?php if ($indiMarkup->type() == TreeNodeMarkupType::firstRepeated()) : ?>
                    <div id="⚶-markup-<?= $indiMarkup->label(); ?>" class="⚶-markup ⚶-markup-type-<?= $indiMarkup->type()->typeClass() ?>">
                        <?= $indiMarkup->label(); ?>
                    </div>
                <?php elseif ($indiMarkup->type() == TreeNodeMarkupType::otherRepeated()) : ?>
                    <div class="⚶-markup ⚶-markup-type-<?= $indiMarkup->type()->typeClass() ?>">
                        <a href="#⚶-markup-<?= $indiMarkup->label(); ?>"><?= $indiMarkup->label(); ?></a>
                    </div>
                <?php endif ?>                
            <?php endif ?>
            <?php if ($indiData !== null) : ?>
                <div class="⚶-data" title="<?= I18N::translate("CoI; Coefficient of Inbreeding"); ?>">
                    <?= I18N::percentage($indiData->coi(), 2); ?>
                </div>  
            <?php endif ?>
            <?= view('vesta-chart-box', [
                'individual' => $record, 
                ]) ?>
        </div>
    </li>    
    <?php if (sizeof($next) > 0) : ?>
        <li class="⚶-famc">
            <div class="⚶-famc">
                <ol class="⚶-fam<?= $leaves ?>">
                    <?php foreach ($next as $nextNode) : ?>
                        <li class="⚶-fam<?= $leaves ?>">
                            <div class="⚶-fam<?= $leaves ?>">
                                <?= view('modules/vesta-pedigree-chart/chart-x', [
                                    'node' => $nextNode, 
                                    ]) ?>                                
                            </div>
                        </li>
                    <?php endforeach ?>                    
                </ol>
            </div>
        </li>
    <?php endif ?>
</ol>    


