<?php

declare(strict_types=1);

use Cissee\Webtrees\Module\ExtendedRelationships\ExtendedPedigreeChartModule;
use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\I18N;

/**
 * @var string               $ajax_url
 * @var int                  $generations
 * @var Individual           $individual
 * @var array                $options
 * @var string               $style
 * @var string               $kind
 * @var array<string,string> $styles
 * @var string               $title
 * @var Tree                 $tree
 */

?>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<form method="post" class="wt-page-options wt-page-options-pedigree-chart d-print-none">
        
    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="xref">
            <?= MoreI18N::xlate('Individual') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select-individual', ['name' => 'xref', 'individual' => $individual, 'tree' => $tree]) ?>
        </div>
    </div>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="generations">
            <?= MoreI18N::xlate('Generations') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select', ['name' => 'generations', 'selected' => $generations, 'options' => $options]) ?>
        </div>
    </div>

    <?php if (ExtendedPedigreeChartModule::KIND_COLLAPSE == $kind) : ?>
        <input type="hidden" name="kind" value="<?= $kind ?>">
    <?php else : ?>
        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="style">
                <?= I18N::translate('Pedigree collapse') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?= view('components/radios-inline', ['name' => 'kind', 'options' => [
                    ExtendedPedigreeChartModule::KIND_COMPACT => I18N::translate('show repeated ancestors once'),
                    ExtendedPedigreeChartModule::KIND_FULL => I18N::translate('show full pedigree'),
                ], 'selected' => $kind]) ?>
            </div>
        </div>
    <?php endif ?>
    
    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="style">
            <?= MoreI18N::xlate('Layout') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/radios-inline', ['name' => 'style', 'options' => $styles, 'selected' => $style]) ?>
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-sm-3 wt-page-options-label"></div>
        <div class="col-sm-9 wt-page-options-value">
            <input class="btn btn-primary" type="submit" value="<?= /* I18N: A button label. */
            MoreI18N::xlate('view') ?>">
        </div>
    </div>

    <?= csrf_field() ?>
</form>

<div class="wt-ajax-load wt-page-content wt-chart wt-chart-pedigree" data-wt-ajax-url="<?= e($ajax_url) ?>"></div>
