<?php

declare(strict_types=1);

use Cissee\WebtreesExt\Services\TreeNode;
use Cissee\WebtreesExt\Services\TreeNodeMarkup;
use Cissee\WebtreesExt\Services\TreeNodeMarkupType;
use Fisharebest\Webtrees\Family;
use Illuminate\Support\Collection;

/**
 * @var TreeNode $node
 */

$record = $node->record();

if ($record instanceof Family) {
  throw new Exception();  
}

$indiMarkups = $node->markups();
$indiData = $node->data();
    
$next = $node->next();
    
$leavesOnly = true;    
foreach ($next as $nextNode) {
    $nextnext = $nextNode->next();
    if (sizeof($nextnext) > 0) {
        $leavesOnly = false;
        break;
    }
}

$leaves = "";
if ($leavesOnly) {
    $leaves = " ⚶-fam-leaves";
}

$indiMarkups = $indiMarkups->filter(function (TreeNodeMarkup $markup): bool {
        return 
            ($markup->type() == TreeNodeMarkupType::firstPathToLca()) || 
            ($markup->type() == TreeNodeMarkupType::otherPathToLca());
    });
    
//TODO: this is problematic for hrefs!
if ($indiMarkups->count() > 3) {
    $mainMarkups = $indiMarkups->slice(0, 2);
    $otherMarkups = $indiMarkups->slice(2);
} else {
    $mainMarkups = $indiMarkups;
    $otherMarkups = new Collection();
}
    

?>

<ol class="⚶-famc">
    <li class="⚶-famc">
        <div class="⚶-famc">
            <?php foreach ($mainMarkups as $mainMarkup) : ?>
                <?php if ($mainMarkup->type() == TreeNodeMarkupType::firstPathToLca()) : ?>
                    <div id="⚶-markup-<?= $mainMarkup->label(); ?>" class="⚶-markup ⚶-markup-type-<?= $mainMarkup->type()->typeClass() ?>">
                        <?= $mainMarkup->label(); ?>
                    </div>
                <?php elseif ($mainMarkup->type() == TreeNodeMarkupType::otherPathToLca()) : ?>
                    <div class="⚶-markup ⚶-markup-type-<?= $mainMarkup->type()->typeClass() ?>">
                        <a href="#⚶-markup-<?= $mainMarkup->label(); ?>"><?= $mainMarkup->label(); ?></a>
                    </div>
                <?php endif ?>
            <?php endforeach ?>
            <?php if ($otherMarkups->isNotEmpty()) : ?>
                <?php if ($otherMarkups->first()->type() == TreeNodeMarkupType::firstPathToLca()) : ?>
                    <div id="⚶-markup-<?= $otherMarkups->first()->label(); ?>" class="⚶-markup ⚶-markup-type-<?= $otherMarkups->first()->type()->typeClass() ?>">
                        <?= '&hellip;' ?>
                    </div>
                <?php elseif ($otherMarkups->first()->type() == TreeNodeMarkupType::otherPathToLca()) : ?>
                    <div class="⚶-markup ⚶-markup-type-<?= $otherMarkups->first()->type()->typeClass() ?>">
                        <a href="#⚶-markup-<?= $otherMarkups->first()->label(); ?>"><?= '&hellip;' ?></a>
                    </div>
                <?php endif ?>
            <?php endif ?>            
            <?= view('vesta-chart-box', [
                'individual' => $record, 
                ]) ?>
        </div>
    </li>    
    <?php if (sizeof($next) > 0) : ?>
        <li class="⚶-famc">
            <div class="⚶-famc">
                <ol class="⚶-fam<?= $leaves ?>">
                    <?php foreach ($next as $nextNode) : ?>
                        <li class="⚶-fam<?= $leaves ?>">
                            <div class="⚶-fam<?= $leaves ?>">
                                <?= view('modules/vesta-lca-chart/chart-x', [
                                    'node' => $nextNode, 
                                    ]) ?>                                
                            </div>
                        </li>
                    <?php endforeach ?>                    
                </ol>
            </div>
        </li>
    <?php endif ?>
</ol>    


