<?php

declare(strict_types=1);

use Cissee\Webtrees\Module\ExtendedRelationships\IndividualsWithPatriarchs;
use Fisharebest\Webtrees\Tree;
//use Illuminate\Support\Collection;

/**
 * @var Collection<Individual> $individuals
 * @var bool                   $sosa
 * @var Tree                   $tree
 */

if (sizeof($individuals) > 0) {
    if ($individuals->first() instanceof IndividualsWithPatriarchs) {
        /** @var IndividualsWithPatriarchs */
        $wrapped = $individuals->first();
    
        //adjusted view
        echo view('lists/individuals-table-with-patriarchs', [
            'individuals' => $wrapped->getOriginalCollection(),
            'patriarchs' => $wrapped->getPatriarchs(),  
            'sosa' => $sosa,
            'tree' => $tree]);
    
        return;
    }
}

//original view
echo view('::lists/individuals-table', [
    'individuals' => $individuals,
    'sosa' => $sosa,
    'tree' => $tree]);
