<?php

declare(strict_types=1);

use Cissee\Webtrees\Module\ExtendedRelationships\SurnameWithPatriarch;
use Fisharebest\Webtrees\Tree;

/**
 * @var bool                      $families
 * @var IndividualListModule|null $module
 * @var array<array<int,string>>  $order
 * @var array<string,string>      $params
 * @var array<array<int>>         $surnames
 * @var Tree                      $tree
 */
if (sizeof($surnames) > 0) {
    $inner = current($surnames);
    if (sizeof($inner) > 0) {
        $leaf = current($inner);
        if ($leaf instanceof SurnameWithPatriarch) {
            //adjusted view
            echo view('lists/surnames-table-with-patriarchs', [
                'helpLink' => $leaf->getHelpLink(),
                'surnames' => $surnames,
                'families' => $families,
                'module' => $module,
                'order' => $order,
                'tree' => $tree]);

            return;
        }
    }
}    

//original view
echo view('::lists/surnames-table', [
    'surnames' => $surnames,
    'families' => $families,
    'module' => $module,
    'order' => $order,
    'params' => $params,
    'tree' => $tree]);
    